### ISSUE TITLE
Registered version is broken

### ISSUE THREAD

**Issue by davidanthoff** [tk3369/CSVReader.jl#3]
Because the `REQUIRE` file is missing all the dependencies of the package. That means no one can use the version that is registered and tagged in METADATA right now.

This is also the scenario why I think one shouldn't have a Project.toml file at this point :) Way too easy to release versions that are completely broken, and if the package didn't have a Project.toml, this would not have slipped through CI.

**Comment by tk3369** [comment]
Oops. Will get it fixed :-)
