### ISSUE TITLE
Update Project.toml

### ISSUE THREAD

**Issue by davidanthoff** [tk3369/CSVReader.jl#8]
I just tried to start another run for my csv-comparison. I had to exclude CSVReader.jl for now because the Project.toml seems to be out of date and that caused problems. Could you maybe fix a few small things and tag a new release, and then I can include it again? In particular:
- Add a compat entry for InternedStrings
- Update the version bounds on DataFrames and any other package, so that it doesn't hold other packages back.

Thanks! No rush, for now I'm just going to exclude the package, so this is more if you want it to be included :)

**Comment by tk3369** [comment]
It's done! Thanks for the ping.
